on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Comment PR with image
        uses: ./
        with:
          message: 'You can also put images... ![Placholder](https://via.placeholder.com/150.png)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}